export const SECTOR_SYMBOLS: Record<string, string[]> = {
  AEROSPACE: [
    'BA','LMT','RTX','NOC','GD','LHX','TDG','HWM','LDOS','KTOS',
    'AVAV','RKLB','SPCE','ASTR','BLDE','JOBY','EVTL','LILM','ACHR',
    'MAXR','SPIR','IRDM','VSAT','GSAT','ASTS','ORBC','GILT',
    'CAT','HON','TXT','PH','ITT','CW','MOG-A','SAIC','HII',
  ],
  QUANTUM: [
    'IBM','GOOGL','MSFT','NVDA','INTC','AMD','QCOM','MRVL',
    'IONQ','RGTI','QUBT','ARQQ','QTUM','DEFN','AMZN','CRM',
    'ORCL','CSCO','TSM','ASML','KLAC','LRCX','AMAT','TXN','LAES','BTQ',
  ],
  LONGEVITY: [
    'GILD','AMGN','REGN','VRTX','BIIB','MRNA','NVAX','BNTX','ILMN',
    'TMO','DHR','A','DXCM','ISRG','VEEV','BSX','MDT','ABT','NTRA',
    'JNJ','PFE','ABBV','LLY','BMY','MRK','GSK','NVO','AZN',
    'UNITY','SEER','TWST','CRSP','EDIT','NTLA','BEAM','VERV',
  ],
  SYNTHETIC_BIO: [
    'TWST','CRSP','EDIT','NTLA','BEAM','VERV','SEER','UNITY','FATE',
    'BLUE','GILD','MRNA','BNTX','NVAX','DNA','SYN','AMRS',
    'CODX','PACB','ILMN','TMO','DHR','A','LIFE','BIO','CDNA',
    'FOLD','RGNX','SGEN','HALO','EVGN','CYTK','ABUS','IMUX',
  ],
  STABLECOIN: [
    'COIN','MSTR','RIOT','MARA','CLSK','BITF','HUT','CAN','BTBT',
    'SQ','PYPL','MA','V','NVDA','AMD','TSLA','HOOD','SOFI',
    'AFRM','UPST','LC','BITO','ARKK','CME',
  ],
  DATACENTER_SEMI: [
    'SMR','BWXT','NEE','AES','BEPC','BE','FLNC','TSLA','LEU','CEG','SO','ETR','DUK','WEC','GEV',
    'EQIX','DLR','IRM','AMT','VRT','ETN','SBGSY','ABB','JCI','TT','NVT','ANET','CSCO',
    'JNPR','CIEN','GLW','LUMN','NVDA','AMD','INTC','AVGO','MRVL','ALAB','ON','CRDO','NVTS',
  ],
  BCI: [
    'NVDA','GOOGL','MSFT','META','AAPL','TSLA','SNAP','MRNA',
    'ILMN','TMO','DHR','A','ISRG','VEEV','BSX','MDT','ABT',
    'JNJ','DXCM','SYNC','LFMD','AXGN','GMED','SENS','PLTR',
  ],
  DATA_CENTER_ENERGY: [
    'SMR','OKLO','BWXT','LTBR','LEU','NEE','AES','BEPC','BE','DUK',
    'FLNC','TSLA','ENPH','STEM','CEG','VST','SO','ETR','WEC','XEL',
    'ABB','ETN','SBGSY','SIEGY','VRT',
  ],
  DATA_CENTER_INFRASTRUCTURE: [
    'EQIX','DLR','AMT','IRM','VRT','ETN','SBGSY','ABB','JCI','TT',
    'NVT','ANET','CSCO','JNPR','CIEN','GLW','LUMN','AKAM','NAVI','IREN',
  ],
  MEGA_CAP_LEADERS: ['AAPL','MSFT','GOOGL','AMZN','NVDA','META','TSLA'],
  CYBERSECURITY: ['PANW','CRWD','ZS','FTNT'],
  SATELLITE_COMMUNICATIONS: ['ASTS','VSAT','ORBC','IRDM'],
  SUBSEA_CABLES: ['TE','CIEN','GLW'],
  OCEAN_PLASTICS: ['MPC'],
  FUTURE_LEADERS: [
    'RKLB','SPCE','BA','LMT','RTX','NOC','MAXR','ASTS',
    'IONQ','RGTI','QUBT','IBM','GOOGL','NVDA','MSFT','LAES','ARQQ','BTQ',
    'UNITY','CRSP','EDIT','NTLA','BEAM','VERV','TWST','GILD','MRNA','NTRA',
    'DNA','TWST','AMRS','CRSP','EDIT','FATE','BLUE','SYN',
    'COIN','MSTR','RIOT','MARA','CLSK','SQ','PYPL','HOOD',
    'NVDA','AMD','JCI','DLR','EQIX','PANW','CRWD','ZS',
    'SMR','OKLO','BWXT','NEE','CEG','VST','SO','ETR','VRT',
    'NVDA','TSLA','META','GOOGL','ISRG','DXCM','BSX','SYNC',
    'NVDA','AMD','GOOGL','MSFT','TSLA','META','PLTR',
  ].filter((v, i, a) => a.indexOf(v) === i), // dedupe
};

export const COMPANY_NAMES: Record<string, string> = {
  // Mega Cap
  AAPL: 'Apple Inc.',
  MSFT: 'Microsoft Corp.',
  GOOGL: 'Alphabet Inc. (A)',
  GOOG: 'Alphabet Inc. (C)',
  AMZN: 'Amazon.com Inc.',
  NVDA: 'NVIDIA Corp.',
  META: 'Meta Platforms Inc.',
  TSLA: 'Tesla Inc.',
  AVGO: 'Broadcom Inc.',
  LLY: 'Eli Lilly and Co.',
  // Finance
  JPM: 'JPMorgan Chase & Co.',
  V: 'Visa Inc.',
  MA: 'Mastercard Inc.',
  BAC: 'Bank of America Corp.',
  WFC: 'Wells Fargo & Co.',
  GS: 'Goldman Sachs Group Inc.',
  MS: 'Morgan Stanley',
  // Tech
  AMD: 'Advanced Micro Devices Inc.',
  INTC: 'Intel Corp.',
  QCOM: 'Qualcomm Inc.',
  IBM: 'IBM Corp.',
  ORCL: 'Oracle Corp.',
  CRM: 'Salesforce Inc.',
  ADBE: 'Adobe Inc.',
  NOW: 'ServiceNow Inc.',
  CSCO: 'Cisco Systems Inc.',
  AMAT: 'Applied Materials Inc.',
  KLAC: 'KLA Corp.',
  LRCX: 'Lam Research Corp.',
  ASML: 'ASML Holding N.V.',
  TSM: 'Taiwan Semiconductor',
  MRVL: 'Marvell Technology Inc.',
  // Healthcare
  JNJ: 'Johnson & Johnson',
  PFE: 'Pfizer Inc.',
  ABBV: 'AbbVie Inc.',
  MRK: 'Merck & Co. Inc.',
  BMY: 'Bristol-Myers Squibb Co.',
  LLY2: 'Eli Lilly and Co.',
  AMGN: 'Amgen Inc.',
  GILD: 'Gilead Sciences Inc.',
  REGN: 'Regeneron Pharmaceuticals Inc.',
  VRTX: 'Vertex Pharmaceuticals Inc.',
  BIIB: 'Biogen Inc.',
  ISRG: 'Intuitive Surgical Inc.',
  MDT: 'Medtronic plc',
  ABT: 'Abbott Laboratories',
  BSX: 'Boston Scientific Corp.',
  DHR: 'Danaher Corp.',
  TMO: 'Thermo Fisher Scientific Inc.',
  ILMN: 'Illumina Inc.',
  DXCM: 'DexCom Inc.',
  NTRA: 'Natera Inc.',
  MRNA: 'Moderna Inc.',
  NVAX: 'Novavax Inc.',
  BNTX: 'BioNTech SE',
  NVO: 'Novo Nordisk A/S',
  AZN: 'AstraZeneca plc',
  GSK: 'GSK plc',
  VEEV: 'Veeva Systems Inc.',
  // Aerospace & Defense
  BA: 'Boeing Co.',
  LMT: 'Lockheed Martin Corp.',
  RTX: 'RTX Corp.',
  NOC: 'Northrop Grumman Corp.',
  GD: 'General Dynamics Corp.',
  LHX: 'L3Harris Technologies Inc.',
  TDG: 'TransDigm Group Inc.',
  HWM: 'Howmet Aerospace Inc.',
  LDOS: 'Leidos Holdings Inc.',
  KTOS: 'Kratos Defense & Security Solutions Inc.',
  AVAV: 'AeroVironment Inc.',
  RKLB: 'Rocket Lab USA Inc.',
  SPCE: 'Virgin Galactic Holdings Inc.',
  ASTR: 'Astra Space Inc.',
  BLDE: 'Blade Air Mobility Inc.',
  JOBY: 'Joby Aviation Inc.',
  ACHR: 'Archer Aviation Inc.',
  MAXR: 'Maxar Technologies Inc.',
  SPIR: 'Spire Global Inc.',
  IRDM: 'Iridium Communications Inc.',
  VSAT: 'Viasat Inc.',
  GSAT: 'Globalstar Inc.',
  ASTS: 'AST SpaceMobile Inc.',
  ORBC: 'ORBCOMM Inc.',
  SAIC: 'Science Applications International Corp.',
  HII: 'Huntington Ingalls Industries Inc.',
  TXT: 'Textron Inc.',
  PH: 'Parker-Hannifin Corp.',
  ITT: 'ITT Inc.',
  CW: 'Curtiss-Wright Corp.',
  CAT: 'Caterpillar Inc.',
  HON: 'Honeywell International Inc.',
  // Quantum Computing
  IONQ: 'IonQ Inc.',
  RGTI: 'Rigetti Computing Inc.',
  QUBT: 'Quantum Computing Inc.',
  ARQQ: 'Arqit Quantum Inc.',
  BTQ: 'BTQ Technologies Corp.',
  LAES: 'SEALSQ Corp.',
  // Biotech / Synthetic Bio
  UNITY: 'Unity Biotechnology Inc.',
  SEER: 'Seer Inc.',
  TWST: 'Twist Bioscience Corp.',
  CRSP: 'CRISPR Therapeutics AG',
  EDIT: 'Editas Medicine Inc.',
  NTLA: 'Intellia Therapeutics Inc.',
  BEAM: 'Beam Therapeutics Inc.',
  VERV: 'Verve Therapeutics Inc.',
  FATE: 'Fate Therapeutics Inc.',
  BLUE: 'bluebird bio Inc.',
  DNA: 'Ginkgo Bioworks Holdings Inc.',
  AMRS: 'Amyris Inc.',
  PACB: 'Pacific Biosciences of California Inc.',
  BIO: 'Bio-Rad Laboratories Inc.',
  CDNA: 'CareDx Inc.',
  FOLD: 'Amicus Therapeutics Inc.',
  RGNX: 'REGENXBIO Inc.',
  HALO: 'Halozyme Therapeutics Inc.',
  CYTK: 'Cytokinetics Inc.',
  // Crypto / Stablecoin
  COIN: 'Coinbase Global Inc.',
  MSTR: 'MicroStrategy Inc.',
  RIOT: 'Riot Platforms Inc.',
  MARA: 'Marathon Digital Holdings Inc.',
  CLSK: 'CleanSpark Inc.',
  BITF: 'Bitfarms Ltd.',
  HUT: 'Hut 8 Corp.',
  HOOD: 'Robinhood Markets Inc.',
  BITO: 'ProShares Bitcoin Strategy ETF',
  ARKK: 'ARK Innovation ETF',
  // Data Center & Energy
  EQIX: 'Equinix Inc.',
  DLR: 'Digital Realty Trust Inc.',
  AMT: 'American Tower Corp.',
  IRM: 'Iron Mountain Inc.',
  VRT: 'Vertiv Holdings Co.',
  ETN: 'Eaton Corp. plc',
  ABB: 'ABB Ltd.',
  JCI: 'Johnson Controls International plc',
  SMR: 'NuScale Power Corp.',
  OKLO: 'Oklo Inc.',
  BWXT: 'BWX Technologies Inc.',
  LTBR: 'Lightbridge Corp.',
  LEU: 'Centrus Energy Corp.',
  CEG: 'Constellation Energy Corp.',
  VST: 'Vistra Corp.',
  NEE: 'NextEra Energy Inc.',
  AES: 'AES Corp.',
  BEPC: 'Brookfield Renewable Corp.',
  BE: 'Bloom Energy Corp.',
  DUK: 'Duke Energy Corp.',
  FLNC: 'Fluence Energy Inc.',
  ENPH: 'Enphase Energy Inc.',
  STEM: 'Stem Inc.',
  SO: 'Southern Co.',
  ETR: 'Entergy Corp.',
  WEC: 'WEC Energy Group Inc.',
  XEL: 'Xcel Energy Inc.',
  // Network / Infrastructure
  ANET: 'Arista Networks Inc.',
  JNPR: 'Juniper Networks Inc.',
  CIEN: 'Ciena Corp.',
  GLW: 'Corning Inc.',
  LUMN: 'Lumen Technologies Inc.',
  AKAM: 'Akamai Technologies Inc.',
  // Cybersecurity
  PANW: 'Palo Alto Networks Inc.',
  CRWD: 'CrowdStrike Holdings Inc.',
  ZS: 'Zscaler Inc.',
  FTNT: 'Fortinet Inc.',
  // Other
  PLTR: 'Palantir Technologies Inc.',
  SQ: 'Block Inc.',
  PYPL: 'PayPal Holdings Inc.',
  SOFI: 'SoFi Technologies Inc.',
  AFRM: 'Affirm Holdings Inc.',
  UPST: 'Upstart Holdings Inc.',
  NFLX: 'Netflix Inc.',
  DIS: 'Walt Disney Co.',
  UBER: 'Uber Technologies Inc.',
  ABNB: 'Airbnb Inc.',
  SNAP: 'Snap Inc.',
  LFMD: 'LifeMD Inc.',
  AXGN: 'AxoGen Inc.',
  GMED: 'Globus Medical Inc.',
  SENS: 'Senseonics Holdings Inc.',
  SYNC: 'Synacor Inc.',
};
